"""add core_web_vitals table

Revision ID: 3e5e04fd5a0d
Revises: 4dffdcd1bf65
Create Date: 2026-08-07 10:27:55.209392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5e04fd5a0d'
down_revision: Union[str, Sequence[str], None] = '4dffdcd1bf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
