"""add gsc_metrics and ga4_metrics tables

Revision ID: 4dffdcd1bf65
Revises: a2709caae3f1
Create Date: 2026-07-27 13:37:12.142599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dffdcd1bf65'
down_revision: Union[str, Sequence[str], None] = 'a2709caae3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ga4_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ga4_metrics_page_url'), 'ga4_metrics', ['page_url'], unique=False)
    op.create_index(op.f('ix_ga4_metrics_site_id'), 'ga4_metrics', ['site_id'], unique=False)
    op.create_index(op.f('ix_ga4_metrics_time'), 'ga4_metrics', ['time'], unique=False)
    op.create_table('gsc_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('position', sa.Numeric(), nullable=True),
    sa.Column('ctr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_metrics_keyword'), 'gsc_metrics', ['keyword'], unique=False)
    op.create_index(op.f('ix_gsc_metrics_page_url'), 'gsc_metrics', ['page_url'], unique=False)
    op.create_index(op.f('ix_gsc_metrics_site_id'), 'gsc_metrics', ['site_id'], unique=False)
    op.create_index(op.f('ix_gsc_metrics_time'), 'gsc_metrics', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsc_metrics_time'), table_name='gsc_metrics')
    op.drop_index(op.f('ix_gsc_metrics_site_id'), table_name='gsc_metrics')
    op.drop_index(op.f('ix_gsc_metrics_page_url'), table_name='gsc_metrics')
    op.drop_index(op.f('ix_gsc_metrics_keyword'), table_name='gsc_metrics')
    op.drop_table('gsc_metrics')
    op.drop_index(op.f('ix_ga4_metrics_time'), table_name='ga4_metrics')
    op.drop_index(op.f('ix_ga4_metrics_site_id'), table_name='ga4_metrics')
    op.drop_index(op.f('ix_ga4_metrics_page_url'), table_name='ga4_metrics')
    op.drop_table('ga4_metrics')
    # ### end Alembic commands ###
