"""make seo metrics fields nullable

Revision ID: 884907be4b44
Revises: 2332bb1e9f2d
Create Date: 2026-07-27 13:15:10.136588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884907be4b44'
down_revision: Union[str, Sequence[str], None] = '2332bb1e9f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_seo_metrics_time'), 'seo_metrics', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_metrics_time'), table_name='seo_metrics')
    # ### end Alembic commands ###
