"""add id column to seo_metrics

Revision ID: c49eccd176bb
Revises: 1074bc6b4e8d
Create Date: 2026-07-20 21:33:28.741548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49eccd176bb'
down_revision: Union[str, Sequence[str], None] = '1074bc6b4e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seo_metrics', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_seo_metrics_site_id'), 'seo_metrics', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_metrics_site_id'), table_name='seo_metrics')
    op.drop_column('seo_metrics', 'id')
    # ### end Alembic commands ###
