"""add ga4 metrics columns to seo_metrics

Revision ID: c7865669313f
Revises: c49eccd176bb
Create Date: 2026-07-27 11:45:47.018713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7865669313f'
down_revision: Union[str, Sequence[str], None] = 'c49eccd176bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seo_metrics', sa.Column('sessions', sa.Integer(), nullable=True))
    op.add_column('seo_metrics', sa.Column('users', sa.Integer(), nullable=True))
    op.add_column('seo_metrics', sa.Column('pageviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_metrics', 'pageviews')
    op.drop_column('seo_metrics', 'users')
    op.drop_column('seo_metrics', 'sessions')
    # ### end Alembic commands ###
