"""add has_used_trial to subscriptions

Revision ID: e3ef1cf8edb3
Revises: 9568309dd3bf
Create Date: 2026-08-17 21:47:59.989515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ef1cf8edb3'
down_revision: Union[str, Sequence[str], None] = '9568309dd3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('has_used_trial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'has_used_trial')
    # ### end Alembic commands ###
