"""add core_web_vitals table

Revision ID: f1577677f98b
Revises: 3e5e04fd5a0d
Create Date: 2026-08-07 10:37:02.089528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1577677f98b'
down_revision: Union[str, Sequence[str], None] = '3e5e04fd5a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_web_vitals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=False),
    sa.Column('niveau', sa.String(), nullable=False),
    sa.Column('lcp', sa.Numeric(), nullable=True),
    sa.Column('lcp_categorie', sa.String(), nullable=True),
    sa.Column('inp', sa.Numeric(), nullable=True),
    sa.Column('inp_categorie', sa.String(), nullable=True),
    sa.Column('cls', sa.Numeric(), nullable=True),
    sa.Column('cls_categorie', sa.String(), nullable=True),
    sa.Column('fcp', sa.Numeric(), nullable=True),
    sa.Column('fcp_categorie', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_web_vitals_page_url'), 'core_web_vitals', ['page_url'], unique=False)
    op.create_index(op.f('ix_core_web_vitals_site_id'), 'core_web_vitals', ['site_id'], unique=False)
    op.create_index(op.f('ix_core_web_vitals_time'), 'core_web_vitals', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_web_vitals_time'), table_name='core_web_vitals')
    op.drop_index(op.f('ix_core_web_vitals_site_id'), table_name='core_web_vitals')
    op.drop_index(op.f('ix_core_web_vitals_page_url'), table_name='core_web_vitals')
    op.drop_table('core_web_vitals')
    # ### end Alembic commands ###
